In [8]:
# Data wrangling
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns
import statsmodels.api as sm

In [10]:
# Load datasets
data_folder = './data/'

headers_character_metadata = ['Wikipedia Movie ID', 'Freebase Movie ID','Movie release date', 'Character name', 'Actor DOB', 
                              'Actor gender', 'Actor height', 'Actor ethnicity', 'Actor name',
                              'Actor age at movie release', 'Freebase character map', 'Freebase character ID', 'Freebase actor ID']
character_metadata = pd.read_csv(data_folder + 'character.metadata.tsv', sep='\t', names=headers_character_metadata)

headers_movie_metadata = ["Wikipedia Movie ID", "Freebase Movie ID", "Movie name", "Movie release date",
                          "Movie box office revenue", "Movie runtime", "Movie languages", "Movie countries",
                          "Movie genres"]
movie_metadata = pd.read_csv(data_folder +'movie.metadata.tsv', sep='\t', names=headers_movie_metadata)

In [11]:
# Add a column of release year to get consistency
character_metadata['Movie release year'] = character_metadata['Movie release date'].str.split('-').str[0].astype('float')
movie_metadata['Movie release year'] = movie_metadata['Movie release date'].str.split('-').str[0].astype('float')

# Add a column of birth year to get consistency
character_metadata['Actor birth year'] = character_metadata['Actor DOB'].str.split('-').str[0].astype('float')

def get_min_and_max(df, variable_name, no_min, no_max):
    array = df[variable_name].fillna(0).unique()
    sorted_array = np.sort(array)
    
    min_values = sorted_array[:no_min]
    max_values = sorted_array[-no_max:]
    
    print(f"{no_min} minimum values of '{variable_name}':")
    print(min_values)

    print(f"{no_max} maximum values of '{variable_name}':")
    print(max_values)

# Find all unique years as sort them
get_min_and_max(df=character_metadata, variable_name='Movie release year', no_min=5, no_max=5)
get_min_and_max(df=character_metadata, variable_name='Actor birth year', no_min=15, no_max=5)

# Define the condition to identify rows where 'Actor birth year' needs to be set to NaN
condition = (character_metadata['Actor birth year'] < 1700) | (character_metadata['Actor birth year'] > 2016)
character_metadata.loc[condition, 'Actor birth year'] = np.nan

get_min_and_max(df=character_metadata, variable_name='Actor height', no_min=15, no_max=15)

# Define the condition to identify rows where height needs to be set to NaN
condition = (character_metadata['Actor height'] > 2.4)
character_metadata.loc[condition, 'Actor height'] = np.nan

get_min_and_max(df=character_metadata, variable_name='Actor age at movie release', no_min=20, no_max=20)


# Define the condition to identify rows where age needs to be set to NaN
condition = (character_metadata['Actor age at movie release'] < 0) | (character_metadata['Actor age at movie release'] > 110)
character_metadata.loc[condition, 'Actor age at movie release'] = np.nan

get_min_and_max(df=movie_metadata, variable_name='Movie runtime', no_min=15, no_max=15)

condition = (movie_metadata['Movie runtime'] > 5*60)
movie_metadata.loc[condition, 'Movie runtime'] = np.nan

get_min_and_max(df=movie_metadata, variable_name='Movie box office revenue', no_min=10, no_max=10)

5 minimum values of 'Movie release year':
[   0. 1010. 1888. 1891. 1893.]
5 maximum values of 'Movie release year':
[2012. 2013. 2014. 2015. 2016.]
15 minimum values of 'Actor birth year':
[   0.   19.  183.  195.  852. 1075. 1474. 1498. 1796. 1804. 1828. 1829.
 1835. 1836. 1837.]
5 maximum values of 'Actor birth year':
[2011. 2050. 2896. 2936. 9900.]
15 minimum values of 'Actor height':
[0.      0.61    0.813   0.83    0.88    0.94    1.      1.06    1.067
 1.07    1.09728 1.1176  1.12    1.14    1.143  ]
15 maximum values of 'Actor height':
[  2.11      2.13      2.134     2.16      2.161     2.18      2.2
   2.24      2.28      2.29      2.31      2.31648   2.356   180.
 510.     ]
20 minimum values of 'Actor age at movie release':
[-7896.  -969.  -937.   -81.   -76.   -65.   -63.   -57.   -53.   -51.
   -50.   -48.   -47.   -44.   -43.   -42.   -39.   -38.   -37.   -36.]
20 maximum values of 'Actor age at movie release':
[ 80.  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.  91. 

In [12]:
movie_metadata

Wikipedia Movie ID Freebase Movie ID  \
0                  975900         /m/03vyhn   
1                 3196793         /m/08yl5d   
2                28463795        /m/0crgdbh   
3                 9363483        /m/0285_cd   
4                  261236         /m/01mrr1   
...                   ...               ...   
81736            35228177        /m/0j7hxnt   
81737            34980460        /m/0g4pl34   
81738             9971909        /m/02pygw1   
81739              913762         /m/03pcrp   
81740            12476867        /m/02w7zz8   

                                              Movie name Movie release date  \
0                                         Ghosts of Mars         2001-08-24   
1      Getting Away with Murder: The JonBenét Ramsey ...         2000-02-16   
2                                            Brun bitter               1988   
3                                       White Of The Eye               1987   
4                                      A Woman in Flames               1983   
...                                                  ...                ...   
81736                           Mermaids: The Body Found         2011-03-19   
81737                                            Knuckle         2011-01-21   
81738                                  Another Nice Mess         1972-09-22   
81739  The Super Dimension Fortress Macross II: Lover...         1992-05-21   
81740                                            Spliced               2002   

       Movie box office revenue  Movie runtime  \
0                    14010832.0           98.0   
1                           NaN           95.0   
2                           NaN           83.0   
3                           NaN          110.0   
4                           NaN          106.0   
...                         ...            ...   
81736                       NaN          120.0   
81737                       NaN           96.0   
81738                       NaN           66.0   
81739                       NaN          150.0   
81740                       NaN           86.0   

                          Movie languages  \
0      {"/m/02h40lc": "English Language"}   
1      {"/m/02h40lc": "English Language"}   
2      {"/m/05f_3": "Norwegian Language"}   
3      {"/m/02h40lc": "English Language"}   
4       {"/m/04306rv": "German Language"}   
...                                   ...   
81736  {"/m/02h40lc": "English Language"}   
81737  {"/m/02h40lc": "English Language"}   
81738  {"/m/02h40lc": "English Language"}   
81739   {"/m/03_9r": "Japanese Language"}   
81740  {"/m/02h40lc": "English Language"}   

                                         Movie countries  \
0              {"/m/09c7w0": "United States of America"}   
1              {"/m/09c7w0": "United States of America"}   
2                                 {"/m/05b4w": "Norway"}   
3                         {"/m/07ssc": "United Kingdom"}   
4                                {"/m/0345h": "Germany"}   
...                                                  ...   
81736          {"/m/09c7w0": "United States of America"}   
81737  {"/m/03rt9": "Ireland", "/m/07ssc": "United Ki...   
81738          {"/m/09c7w0": "United States of America"}   
81739                              {"/m/03_3d": "Japan"}   
81740                            {"/m/0d060g": "Canada"}   

                                            Movie genres  Movie release year  
0      {"/m/01jfsb": "Thriller", "/m/06n90": "Science...              2001.0  
1      {"/m/02n4kr": "Mystery", "/m/03bxz7": "Biograp...              2000.0  
2      {"/m/0lsxr": "Crime Fiction", "/m/07s9rl0": "D...              1988.0  
3      {"/m/01jfsb": "Thriller", "/m/0glj9q": "Erotic...              1987.0  
4                                {"/m/07s9rl0": "Drama"}              1983.0  
...                                                  ...                 ...  
81736                            {"/m/07s9rl0": "Drama"}              2011.0 